// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.2
// source: sdk/plugin/pluginv1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterceptAction int32

const (
	InterceptAction_INTERCEPT_ACTION_PASSTHROUGH InterceptAction = 0
	InterceptAction_INTERCEPT_ACTION_RESHAPE_REQ InterceptAction = 1
	InterceptAction_INTERCEPT_ACTION_RESPOND     InterceptAction = 2
)

// Enum value maps for InterceptAction.
var (
	InterceptAction_name = map[int32]string{
		0: "INTERCEPT_ACTION_PASSTHROUGH",
		1: "INTERCEPT_ACTION_RESHAPE_REQ",
		2: "INTERCEPT_ACTION_RESPOND",
	}
	InterceptAction_value = map[string]int32{
		"INTERCEPT_ACTION_PASSTHROUGH": 0,
		"INTERCEPT_ACTION_RESHAPE_REQ": 1,
		"INTERCEPT_ACTION_RESPOND":     2,
	}
)

func (x InterceptAction) Enum() *InterceptAction {
	p := new(InterceptAction)
	*p = x
	return p
}

func (x InterceptAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterceptAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_plugin_pluginv1_plugin_proto_enumTypes[0].Descriptor()
}

func (InterceptAction) Type() protoreflect.EnumType {
	return &file_sdk_plugin_pluginv1_plugin_proto_enumTypes[0]
}

func (x InterceptAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterceptAction.Descriptor instead.
func (InterceptAction) EnumDescriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pubkey        string                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Kind          int32                  `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Sig           string                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Event) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Authors       []string               `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
	Kinds         []int32                `protobuf:"varint,3,rep,packed,name=kinds,proto3" json:"kinds,omitempty"`
	Since         *int64                 `protobuf:"varint,4,opt,name=since,proto3,oneof" json:"since,omitempty"`
	Until         *int64                 `protobuf:"varint,5,opt,name=until,proto3,oneof" json:"until,omitempty"`
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Search        string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	TagFilters    []*TagFilter           `protobuf:"bytes,8,rep,name=tag_filters,json=tagFilters,proto3" json:"tag_filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Filter) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Filter) GetKinds() []int32 {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Filter) GetSince() int64 {
	if x != nil && x.Since != nil {
		return *x.Since
	}
	return 0
}

func (x *Filter) GetUntil() int64 {
	if x != nil && x.Until != nil {
		return *x.Until
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *Filter) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *Filter) GetTagFilters() []*TagFilter {
	if x != nil {
		return x.TagFilters
	}
	return nil
}

type TagFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // letter without '#', e.g. "g"
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagFilter) Reset() {
	*x = TagFilter{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilter) ProtoMessage() {}

func (x *TagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilter.ProtoReflect.Descriptor instead.
func (*TagFilter) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *TagFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TrafficSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTypes  []string               `protobuf:"bytes,1,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"` // EVENT, REQ, CLOSE, AUTH
	Kinds         []int32                `protobuf:"varint,2,rep,packed,name=kinds,proto3" json:"kinds,omitempty"`
	ReqHasSearch  bool                   `protobuf:"varint,3,opt,name=req_has_search,json=reqHasSearch,proto3" json:"req_has_search,omitempty"`
	ReqTagNames   []string               `protobuf:"bytes,4,rep,name=req_tag_names,json=reqTagNames,proto3" json:"req_tag_names,omitempty"`
	InterceptReq  bool                   `protobuf:"varint,5,opt,name=intercept_req,json=interceptReq,proto3" json:"intercept_req,omitempty"`
	Observe       bool                   `protobuf:"varint,6,opt,name=observe,proto3" json:"observe,omitempty"`
	OnStoredEvent bool                   `protobuf:"varint,7,opt,name=on_stored_event,json=onStoredEvent,proto3" json:"on_stored_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficSubscription) Reset() {
	*x = TrafficSubscription{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSubscription) ProtoMessage() {}

func (x *TrafficSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSubscription.ProtoReflect.Descriptor instead.
func (*TrafficSubscription) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficSubscription) GetMessageTypes() []string {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

func (x *TrafficSubscription) GetKinds() []int32 {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *TrafficSubscription) GetReqHasSearch() bool {
	if x != nil {
		return x.ReqHasSearch
	}
	return false
}

func (x *TrafficSubscription) GetReqTagNames() []string {
	if x != nil {
		return x.ReqTagNames
	}
	return nil
}

func (x *TrafficSubscription) GetInterceptReq() bool {
	if x != nil {
		return x.InterceptReq
	}
	return false
}

func (x *TrafficSubscription) GetObserve() bool {
	if x != nil {
		return x.Observe
	}
	return false
}

func (x *TrafficSubscription) GetOnStoredEvent() bool {
	if x != nil {
		return x.OnStoredEvent
	}
	return false
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    int32                  `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	SettingsJson  string                 `protobuf:"bytes,2,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeRequest) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *HandshakeRequest) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

type HandshakeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion          int32                  `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	PluginId            string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version             string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities        []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Subscriptions       []*TrafficSubscription `protobuf:"bytes,6,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	InterceptDeadlineMs int32                  `protobuf:"varint,7,opt,name=intercept_deadline_ms,json=interceptDeadlineMs,proto3" json:"intercept_deadline_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeResponse) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeResponse) GetSubscriptions() []*TrafficSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *HandshakeResponse) GetInterceptDeadlineMs() int32 {
	if x != nil {
		return x.InterceptDeadlineMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	SubId         string                 `protobuf:"bytes,3,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ObserveRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ObserveRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ObserveRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *ObserveRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{10}
}

type InterceptREQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptREQRequest) Reset() {
	*x = InterceptREQRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptREQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptREQRequest) ProtoMessage() {}

func (x *InterceptREQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptREQRequest.ProtoReflect.Descriptor instead.
func (*InterceptREQRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *InterceptREQRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *InterceptREQRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type InterceptREQResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Action              InterceptAction        `protobuf:"varint,1,opt,name=action,proto3,enum=congee.plugin.v1.InterceptAction" json:"action,omitempty"`
	ReshapeFilters      []*Filter              `protobuf:"bytes,2,rep,name=reshape_filters,json=reshapeFilters,proto3" json:"reshape_filters,omitempty"`
	EventIds            []string               `protobuf:"bytes,3,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	SubscriptionFilters []*Filter              `protobuf:"bytes,4,rep,name=subscription_filters,json=subscriptionFilters,proto3" json:"subscription_filters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InterceptREQResponse) Reset() {
	*x = InterceptREQResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptREQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptREQResponse) ProtoMessage() {}

func (x *InterceptREQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptREQResponse.ProtoReflect.Descriptor instead.
func (*InterceptREQResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *InterceptREQResponse) GetAction() InterceptAction {
	if x != nil {
		return x.Action
	}
	return InterceptAction_INTERCEPT_ACTION_PASSTHROUGH
}

func (x *InterceptREQResponse) GetReshapeFilters() []*Filter {
	if x != nil {
		return x.ReshapeFilters
	}
	return nil
}

func (x *InterceptREQResponse) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *InterceptREQResponse) GetSubscriptionFilters() []*Filter {
	if x != nil {
		return x.SubscriptionFilters
	}
	return nil
}

type OnStoredEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Stored        bool                   `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnStoredEventRequest) Reset() {
	*x = OnStoredEventRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnStoredEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnStoredEventRequest) ProtoMessage() {}

func (x *OnStoredEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnStoredEventRequest.ProtoReflect.Descriptor instead.
func (*OnStoredEventRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *OnStoredEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *OnStoredEventRequest) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

type OnStoredEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnStoredEventResponse) Reset() {
	*x = OnStoredEventResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnStoredEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnStoredEventResponse) ProtoMessage() {}

func (x *OnStoredEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnStoredEventResponse.ProtoReflect.Descriptor instead.
func (*OnStoredEventResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{14}
}

type ApplySettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingsJson  string                 `protobuf:"bytes,1,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySettingsRequest) Reset() {
	*x = ApplySettingsRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySettingsRequest) ProtoMessage() {}

func (x *ApplySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySettingsRequest.ProtoReflect.Descriptor instead.
func (*ApplySettingsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ApplySettingsRequest) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

type ApplySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*TrafficSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySettingsResponse) Reset() {
	*x = ApplySettingsResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySettingsResponse) ProtoMessage() {}

func (x *ApplySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySettingsResponse.ProtoReflect.Descriptor instead.
func (*ApplySettingsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ApplySettingsResponse) GetSubscriptions() []*TrafficSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type AdminActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionRequest) Reset() {
	*x = AdminActionRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionRequest) ProtoMessage() {}

func (x *AdminActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionRequest.ProtoReflect.Descriptor instead.
func (*AdminActionRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminActionRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type AdminActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   string                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionResponse) Reset() {
	*x = AdminActionResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionResponse) ProtoMessage() {}

func (x *AdminActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionResponse.ProtoReflect.Descriptor instead.
func (*AdminActionResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *AdminActionResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{19}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *QueryEventsRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByIDsRequest) Reset() {
	*x = GetEventsByIDsRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByIDsRequest) ProtoMessage() {}

func (x *GetEventsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *GetEventsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetEventsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByIDsResponse) Reset() {
	*x = GetEventsByIDsResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByIDsResponse) ProtoMessage() {}

func (x *GetEventsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *GetEventsByIDsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_pluginv1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP(), []int{26}
}

var File_sdk_plugin_pluginv1_plugin_proto protoreflect.FileDescriptor

const file_sdk_plugin_pluginv1_plugin_proto_rawDesc = "" +
	"\n" +
	" sdk/plugin/pluginv1/plugin.proto\x12\x10congee.plugin.v1\"\xb9\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\x05R\x04kind\x12)\n" +
	"\x04tags\x18\x05 \x03(\v2\x15.congee.plugin.v1.TagR\x04tags\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x10\n" +
	"\x03sig\x18\a \x01(\tR\x03sig\"\x1d\n" +
	"\x03Tag\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x8f\x02\n" +
	"\x06Filter\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x18\n" +
	"\aauthors\x18\x02 \x03(\tR\aauthors\x12\x14\n" +
	"\x05kinds\x18\x03 \x03(\x05R\x05kinds\x12\x19\n" +
	"\x05since\x18\x04 \x01(\x03H\x00R\x05since\x88\x01\x01\x12\x19\n" +
	"\x05until\x18\x05 \x01(\x03H\x01R\x05until\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\x12<\n" +
	"\vtag_filters\x18\b \x03(\v2\x1b.congee.plugin.v1.TagFilterR\n" +
	"tagFiltersB\b\n" +
	"\x06_sinceB\b\n" +
	"\x06_untilB\b\n" +
	"\x06_limit\"7\n" +
	"\tTagFilter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x81\x02\n" +
	"\x13TrafficSubscription\x12#\n" +
	"\rmessage_types\x18\x01 \x03(\tR\fmessageTypes\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\x05R\x05kinds\x12$\n" +
	"\x0ereq_has_search\x18\x03 \x01(\bR\freqHasSearch\x12\"\n" +
	"\rreq_tag_names\x18\x04 \x03(\tR\vreqTagNames\x12#\n" +
	"\rintercept_req\x18\x05 \x01(\bR\finterceptReq\x12\x18\n" +
	"\aobserve\x18\x06 \x01(\bR\aobserve\x12&\n" +
	"\x0fon_stored_event\x18\a \x01(\bR\ronStoredEvent\"X\n" +
	"\x10HandshakeRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\x05R\n" +
	"apiVersion\x12#\n" +
	"\rsettings_json\x18\x02 \x01(\tR\fsettingsJson\"\xa4\x02\n" +
	"\x11HandshakeResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\x05R\n" +
	"apiVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12K\n" +
	"\rsubscriptions\x18\x06 \x03(\v2%.congee.plugin.v1.TrafficSubscriptionR\rsubscriptions\x122\n" +
	"\x15intercept_deadline_ms\x18\a \x01(\x05R\x13interceptDeadlineMs\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x0eObserveRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x17.congee.plugin.v1.EventR\x05event\x12\x15\n" +
	"\x06sub_id\x18\x03 \x01(\tR\x05subId\x122\n" +
	"\afilters\x18\x04 \x03(\v2\x18.congee.plugin.v1.FilterR\afilters\"\x11\n" +
	"\x0fObserveResponse\"`\n" +
	"\x13InterceptREQRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\x122\n" +
	"\afilters\x18\x02 \x03(\v2\x18.congee.plugin.v1.FilterR\afilters\"\xfe\x01\n" +
	"\x14InterceptREQResponse\x129\n" +
	"\x06action\x18\x01 \x01(\x0e2!.congee.plugin.v1.InterceptActionR\x06action\x12A\n" +
	"\x0freshape_filters\x18\x02 \x03(\v2\x18.congee.plugin.v1.FilterR\x0ereshapeFilters\x12\x1b\n" +
	"\tevent_ids\x18\x03 \x03(\tR\beventIds\x12K\n" +
	"\x14subscription_filters\x18\x04 \x03(\v2\x18.congee.plugin.v1.FilterR\x13subscriptionFilters\"]\n" +
	"\x14OnStoredEventRequest\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.congee.plugin.v1.EventR\x05event\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\bR\x06stored\"\x17\n" +
	"\x15OnStoredEventResponse\";\n" +
	"\x14ApplySettingsRequest\x12#\n" +
	"\rsettings_json\x18\x01 \x01(\tR\fsettingsJson\"d\n" +
	"\x15ApplySettingsResponse\x12K\n" +
	"\rsubscriptions\x18\x01 \x03(\v2%.congee.plugin.v1.TrafficSubscriptionR\rsubscriptions\"K\n" +
	"\x12AdminActionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"8\n" +
	"\x13AdminActionResponse\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\tR\vpayloadJson\"\x0f\n" +
	"\rStatusRequest\":\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"H\n" +
	"\x12QueryEventsRequest\x122\n" +
	"\afilters\x18\x01 \x03(\v2\x18.congee.plugin.v1.FilterR\afilters\"F\n" +
	"\x13QueryEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.congee.plugin.v1.EventR\x06events\")\n" +
	"\x15GetEventsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"I\n" +
	"\x16GetEventsByIDsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.congee.plugin.v1.EventR\x06events\"\xb9\x01\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\x06fields\x18\x03 \x03(\v2(.congee.plugin.v1.LogRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\r\n" +
	"\vLogResponse*s\n" +
	"\x0fInterceptAction\x12 \n" +
	"\x1cINTERCEPT_ACTION_PASSTHROUGH\x10\x00\x12 \n" +
	"\x1cINTERCEPT_ACTION_RESHAPE_REQ\x10\x01\x12\x1c\n" +
	"\x18INTERCEPT_ACTION_RESPOND\x10\x022\xc7\x05\n" +
	"\x06Plugin\x12T\n" +
	"\tHandshake\x12\".congee.plugin.v1.HandshakeRequest\x1a#.congee.plugin.v1.HandshakeResponse\x12K\n" +
	"\x06Health\x12\x1f.congee.plugin.v1.HealthRequest\x1a .congee.plugin.v1.HealthResponse\x12N\n" +
	"\aObserve\x12 .congee.plugin.v1.ObserveRequest\x1a!.congee.plugin.v1.ObserveResponse\x12]\n" +
	"\fInterceptREQ\x12%.congee.plugin.v1.InterceptREQRequest\x1a&.congee.plugin.v1.InterceptREQResponse\x12`\n" +
	"\rOnStoredEvent\x12&.congee.plugin.v1.OnStoredEventRequest\x1a'.congee.plugin.v1.OnStoredEventResponse\x12`\n" +
	"\rApplySettings\x12&.congee.plugin.v1.ApplySettingsRequest\x1a'.congee.plugin.v1.ApplySettingsResponse\x12Z\n" +
	"\vAdminAction\x12$.congee.plugin.v1.AdminActionRequest\x1a%.congee.plugin.v1.AdminActionResponse\x12K\n" +
	"\x06Status\x12\x1f.congee.plugin.v1.StatusRequest\x1a .congee.plugin.v1.StatusResponse2\x8b\x02\n" +
	"\x04Host\x12Z\n" +
	"\vQueryEvents\x12$.congee.plugin.v1.QueryEventsRequest\x1a%.congee.plugin.v1.QueryEventsResponse\x12c\n" +
	"\x0eGetEventsByIDs\x12'.congee.plugin.v1.GetEventsByIDsRequest\x1a(.congee.plugin.v1.GetEventsByIDsResponse\x12B\n" +
	"\x03Log\x12\x1c.congee.plugin.v1.LogRequest\x1a\x1d.congee.plugin.v1.LogResponseB3Z1github.com/michmich112/congee/sdk/plugin/pluginv1b\x06proto3"

var (
	file_sdk_plugin_pluginv1_plugin_proto_rawDescOnce sync.Once
	file_sdk_plugin_pluginv1_plugin_proto_rawDescData []byte
)

func file_sdk_plugin_pluginv1_plugin_proto_rawDescGZIP() []byte {
	file_sdk_plugin_pluginv1_plugin_proto_rawDescOnce.Do(func() {
		file_sdk_plugin_pluginv1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_plugin_pluginv1_plugin_proto_rawDesc), len(file_sdk_plugin_pluginv1_plugin_proto_rawDesc)))
	})
	return file_sdk_plugin_pluginv1_plugin_proto_rawDescData
}

var file_sdk_plugin_pluginv1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_plugin_pluginv1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_sdk_plugin_pluginv1_plugin_proto_goTypes = []any{
	(InterceptAction)(0),           // 0: congee.plugin.v1.InterceptAction
	(*Event)(nil),                  // 1: congee.plugin.v1.Event
	(*Tag)(nil),                    // 2: congee.plugin.v1.Tag
	(*Filter)(nil),                 // 3: congee.plugin.v1.Filter
	(*TagFilter)(nil),              // 4: congee.plugin.v1.TagFilter
	(*TrafficSubscription)(nil),    // 5: congee.plugin.v1.TrafficSubscription
	(*HandshakeRequest)(nil),       // 6: congee.plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil),      // 7: congee.plugin.v1.HandshakeResponse
	(*HealthRequest)(nil),          // 8: congee.plugin.v1.HealthRequest
	(*HealthResponse)(nil),         // 9: congee.plugin.v1.HealthResponse
	(*ObserveRequest)(nil),         // 10: congee.plugin.v1.ObserveRequest
	(*ObserveResponse)(nil),        // 11: congee.plugin.v1.ObserveResponse
	(*InterceptREQRequest)(nil),    // 12: congee.plugin.v1.InterceptREQRequest
	(*InterceptREQResponse)(nil),   // 13: congee.plugin.v1.InterceptREQResponse
	(*OnStoredEventRequest)(nil),   // 14: congee.plugin.v1.OnStoredEventRequest
	(*OnStoredEventResponse)(nil),  // 15: congee.plugin.v1.OnStoredEventResponse
	(*ApplySettingsRequest)(nil),   // 16: congee.plugin.v1.ApplySettingsRequest
	(*ApplySettingsResponse)(nil),  // 17: congee.plugin.v1.ApplySettingsResponse
	(*AdminActionRequest)(nil),     // 18: congee.plugin.v1.AdminActionRequest
	(*AdminActionResponse)(nil),    // 19: congee.plugin.v1.AdminActionResponse
	(*StatusRequest)(nil),          // 20: congee.plugin.v1.StatusRequest
	(*StatusResponse)(nil),         // 21: congee.plugin.v1.StatusResponse
	(*QueryEventsRequest)(nil),     // 22: congee.plugin.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil),    // 23: congee.plugin.v1.QueryEventsResponse
	(*GetEventsByIDsRequest)(nil),  // 24: congee.plugin.v1.GetEventsByIDsRequest
	(*GetEventsByIDsResponse)(nil), // 25: congee.plugin.v1.GetEventsByIDsResponse
	(*LogRequest)(nil),             // 26: congee.plugin.v1.LogRequest
	(*LogResponse)(nil),            // 27: congee.plugin.v1.LogResponse
	nil,                            // 28: congee.plugin.v1.LogRequest.FieldsEntry
}
var file_sdk_plugin_pluginv1_plugin_proto_depIdxs = []int32{
	2,  // 0: congee.plugin.v1.Event.tags:type_name -> congee.plugin.v1.Tag
	4,  // 1: congee.plugin.v1.Filter.tag_filters:type_name -> congee.plugin.v1.TagFilter
	5,  // 2: congee.plugin.v1.HandshakeResponse.subscriptions:type_name -> congee.plugin.v1.TrafficSubscription
	1,  // 3: congee.plugin.v1.ObserveRequest.event:type_name -> congee.plugin.v1.Event
	3,  // 4: congee.plugin.v1.ObserveRequest.filters:type_name -> congee.plugin.v1.Filter
	3,  // 5: congee.plugin.v1.InterceptREQRequest.filters:type_name -> congee.plugin.v1.Filter
	0,  // 6: congee.plugin.v1.InterceptREQResponse.action:type_name -> congee.plugin.v1.InterceptAction
	3,  // 7: congee.plugin.v1.InterceptREQResponse.reshape_filters:type_name -> congee.plugin.v1.Filter
	3,  // 8: congee.plugin.v1.InterceptREQResponse.subscription_filters:type_name -> congee.plugin.v1.Filter
	1,  // 9: congee.plugin.v1.OnStoredEventRequest.event:type_name -> congee.plugin.v1.Event
	5,  // 10: congee.plugin.v1.ApplySettingsResponse.subscriptions:type_name -> congee.plugin.v1.TrafficSubscription
	3,  // 11: congee.plugin.v1.QueryEventsRequest.filters:type_name -> congee.plugin.v1.Filter
	1,  // 12: congee.plugin.v1.QueryEventsResponse.events:type_name -> congee.plugin.v1.Event
	1,  // 13: congee.plugin.v1.GetEventsByIDsResponse.events:type_name -> congee.plugin.v1.Event
	28, // 14: congee.plugin.v1.LogRequest.fields:type_name -> congee.plugin.v1.LogRequest.FieldsEntry
	6,  // 15: congee.plugin.v1.Plugin.Handshake:input_type -> congee.plugin.v1.HandshakeRequest
	8,  // 16: congee.plugin.v1.Plugin.Health:input_type -> congee.plugin.v1.HealthRequest
	10, // 17: congee.plugin.v1.Plugin.Observe:input_type -> congee.plugin.v1.ObserveRequest
	12, // 18: congee.plugin.v1.Plugin.InterceptREQ:input_type -> congee.plugin.v1.InterceptREQRequest
	14, // 19: congee.plugin.v1.Plugin.OnStoredEvent:input_type -> congee.plugin.v1.OnStoredEventRequest
	16, // 20: congee.plugin.v1.Plugin.ApplySettings:input_type -> congee.plugin.v1.ApplySettingsRequest
	18, // 21: congee.plugin.v1.Plugin.AdminAction:input_type -> congee.plugin.v1.AdminActionRequest
	20, // 22: congee.plugin.v1.Plugin.Status:input_type -> congee.plugin.v1.StatusRequest
	22, // 23: congee.plugin.v1.Host.QueryEvents:input_type -> congee.plugin.v1.QueryEventsRequest
	24, // 24: congee.plugin.v1.Host.GetEventsByIDs:input_type -> congee.plugin.v1.GetEventsByIDsRequest
	26, // 25: congee.plugin.v1.Host.Log:input_type -> congee.plugin.v1.LogRequest
	7,  // 26: congee.plugin.v1.Plugin.Handshake:output_type -> congee.plugin.v1.HandshakeResponse
	9,  // 27: congee.plugin.v1.Plugin.Health:output_type -> congee.plugin.v1.HealthResponse
	11, // 28: congee.plugin.v1.Plugin.Observe:output_type -> congee.plugin.v1.ObserveResponse
	13, // 29: congee.plugin.v1.Plugin.InterceptREQ:output_type -> congee.plugin.v1.InterceptREQResponse
	15, // 30: congee.plugin.v1.Plugin.OnStoredEvent:output_type -> congee.plugin.v1.OnStoredEventResponse
	17, // 31: congee.plugin.v1.Plugin.ApplySettings:output_type -> congee.plugin.v1.ApplySettingsResponse
	19, // 32: congee.plugin.v1.Plugin.AdminAction:output_type -> congee.plugin.v1.AdminActionResponse
	21, // 33: congee.plugin.v1.Plugin.Status:output_type -> congee.plugin.v1.StatusResponse
	23, // 34: congee.plugin.v1.Host.QueryEvents:output_type -> congee.plugin.v1.QueryEventsResponse
	25, // 35: congee.plugin.v1.Host.GetEventsByIDs:output_type -> congee.plugin.v1.GetEventsByIDsResponse
	27, // 36: congee.plugin.v1.Host.Log:output_type -> congee.plugin.v1.LogResponse
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sdk_plugin_pluginv1_plugin_proto_init() }
func file_sdk_plugin_pluginv1_plugin_proto_init() {
	if File_sdk_plugin_pluginv1_plugin_proto != nil {
		return
	}
	file_sdk_plugin_pluginv1_plugin_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_plugin_pluginv1_plugin_proto_rawDesc), len(file_sdk_plugin_pluginv1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sdk_plugin_pluginv1_plugin_proto_goTypes,
		DependencyIndexes: file_sdk_plugin_pluginv1_plugin_proto_depIdxs,
		EnumInfos:         file_sdk_plugin_pluginv1_plugin_proto_enumTypes,
		MessageInfos:      file_sdk_plugin_pluginv1_plugin_proto_msgTypes,
	}.Build()
	File_sdk_plugin_pluginv1_plugin_proto = out.File
	file_sdk_plugin_pluginv1_plugin_proto_goTypes = nil
	file_sdk_plugin_pluginv1_plugin_proto_depIdxs = nil
}
